inputDir:
  - F:\logs\FIRST-11590\5-23-2016 - Gems-GP-GC-Client Logs\GEMS Logs
es:
  url: localhost
  port: 9300
  index: gems-test
  doctype: gems
lineHeader: ^\d\d\d\d-\d\d-\d\dT
filters:
  - regex: ^(?<timestamp>[^\s]+)[\s]+CEF:1\s*\|\s*[^\s]*\s*\|\s*(?<appName>[^\s]*)\s*\|\s*[^\s]*\s*\|\s*(?<level>[^\s]+)\s*\|\s*[^\s]*\s*\|\s*[^\s]*\s*\|\s*ID=[^\s]*[\s]+THR=(?<thr>[^\s]+)[\s]+CAT=(?<cat>[^\s]+)[\s]+MSG=(?<message>.+)
    field:
  - regex: (?<email>[\w\.\-]+@[\w\.\-]+)
  - regex: (?<exception>[\w\.]+Exception).*[\r\n]+\tat 
  - regex: Start running the (master|leader)
    addTag: producer
  - regex: Assigning (?<assignEws>[0-9]{2,}+|[1-9]) users to EWS-Listeners
  - regex: Assigning (?<assignAutod>[0-9]{2,}+|[1-9]) users .*for autodiscover
  - regex: ^Started sync request
    addTag: start_sync
    hasProp: email
  - regex: finished syncing,
    addTag: end_sync
    hasProp: email
  - regex: Received notification event
    addTag: recv_note
    hasProp: email
  - regex: Calling (?<push>\w+) Relay at
    hasProp: email
  - latency:
      startTag: start_sync
      endTag: end_sync
      id: email
      timeout: 300
      countTags: recv_note 