cfg:
  lineHeader: ^\d\d\d\d-\d\d-\d\dT
  filters:
  	- regex: ^(?<timestamp>[^\s]+)[\s]+CEF:1\s*\|\s*[^\s]*\s*\|\s*(?<appName>[^\s]*)\s*\|\s*[^\s]*\s*\|\s*(?<level>[^\s]+)\s*\|\s*[^\s]*\s*\|\s*[^\s]*\s*\|\s*ID=[^\s]*[\s]+THR=(?<thr>[^\s]+)[\s]+CAT=(?<cat>[^\s]+)[\s]+MSG=(?<message>.+)
  	- regex: (?<email>[\w\.\-]+@[\w\.\-]+)
    - regex: ^Started sync request
      addTag: start_sync
      hasProp: email
    - regex: finished syncing,
      addTag: end_sync
      hasProp: email
    - regex: Received notification event
      addTag: recv_note
      hasProp: email
    - regex: Calling (?<push>\w+) Relay at
      hasProp: email